version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sermorpheus_postgres
    environment:
      POSTGRES_DB: sermorpheus
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sermorpheus"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sermorpheus_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: sermorpheus_app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/sermorpheus?sslmode=disable
      - PORT=8080
      - ENVIRONMENT=production
      - BSC_RPC_URL=https://data-seed-prebsc-1-s1.binance.org:8545
      - USDT_CONTRACT=0x337610d27c682E347C9cD60BD4b3b107C9d34dDd
      - PLATFORM_FEE_PERCENT=1.2
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: